### ISSUE TITLE
Fasta saving file does not work on MacOS

### ISSUE THREAD

**Issue by AnnaNenarokova** [Seraff/taxus#17]
While trying to save an out fasta, received the following errors:

```
Unhandled Promise Rejection
TypeError: Cannot read property 'path' of undefined
    at file:///Applications/taxus.app/Contents/Resources/app.asar/js/scripts.js:199:55
```

```
Unhandled Error
TypeError: Cannot read property 'out_path' of undefined
    at save_fasta_as_action (file:///Applications/taxus.app/Contents/Resources/app.asar/js/scripts.js:279:73)
    at CallbacksRegistry.apply (electron/js2c/renderer_init.js:1917:29)
    at electron/js2c/renderer_init.js:1379:21
    at EventEmitter.<anonymous> (electron/js2c/renderer_init.js:1359:7)
    at Object.onMessage (electron/js2c/renderer_init.js:1572:16)
```

**Comment by Seraff** [comment]
Version 0.3.1 fixes this
